
server:
  port: 7003

spring:
  jpa:
    hibernate:
      ddl-auto: update
      # en produccion es ddl-auto:none
    datasource:
      url: jdb:mysql://localhost/review-db
      username: user
      password: pwd

---
spring.config:
    activate:
      on-profile: docker
server:
  port: 8080

# datasource para docker
spring:
  datasource:
    url: jdbc:mysql://mysql/review-db